[package]
name = "open-ipmsg"
version = "0.1.0"
description = "跨平台 IP Messenger 客户端（Tauri v2，仿微信PC界面）"
authors = ["allen"]
edition = "2021"

[lib]
name = "open_ipmsg_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6", features = [] }

[dependencies]
tauri = { version = "2.11", features = [] }
tauri-plugin-dialog = "2.7"
tauri-plugin-opener = "2.5"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "time",
    "sync",
    "fs",
    "io-util",
] }
encoding_rs = "0.8"
local-ip-address = "0.6"
hostname = "0.4"

[features]
net_debug = []

[profile.release]
strip = true
lto = true
codegen-units = 1
